### ISSUE TITLE
Accueil

### ISSUE THREAD

**Issue by Raul6469** [IssouProjects/Ubirb#11]

**Comment by AmosTrask** [comment]
Ya pas d'accueil en faite?

**Comment by Raul6469** [comment]
On peut en faire un, même si c'est pas obligatoire, par exemple un écran avant la connexion/inscription pour présenter les fonctionnalités, ça se fait souvent. Mais à part ça, je vois pas trop où est-ce qu'on pourrait en avoir ailleurs 😕

**Comment by Raul6469** [comment]
Ça pourrait être genre un fil d'actualité

**Comment by QuentinJoder** [comment]
On a décidé de ne pas en faire, on ferme.
