### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by Raul6469** [IssouProjects/Ubirb#17]

**Comment by Raul6469** [comment]
Est-ce qu'on implémente ça ? Et si oui, comment est-ce que vous voulez faire ?

**Comment by TimotheeDurand** [comment]
0 idée c'est pour ça que j'ai pas fais de maquettes

**Comment by AmosTrask** [comment]
non

**Comment by TimotheeDurand** [comment]
d'ailleurs la même question se pose pour l'accueil
