### ISSUE TITLE
Faire les messages pour "Je reçois"

### ISSUE THREAD

**Issue by QuentinJoder** [IssouProjects/Ubirb#51]

**Comment by AmosTrask** [comment]
Il y a vraiment besoin? Au final ça revient à refaire les mêmes messages que pour j'offre mais inversé.

**Comment by TimotheeDurand** [comment]
ouais ce serait pas mal d'avoir un truc cohérent vu que dans la liste des transaction en cours on en a une avec Pierre Descraques

**Comment by AmosTrask** [comment]
ah j'avais pas fais gaffe à ça, dans ce cas je suis d'accord :)

**Comment by AmosTrask** [comment]
je vais la faire, vu que c'est mon bordel le fragment message x)
