### ISSUE TITLE
Réorganiser le Navigation drawer

### ISSUE THREAD

**Issue by QuentinJoder** [IssouProjects/Ubirb#54]
Je pense qu'il serait plus logique de mettre "Mes transactions" en cours entre "Mes demandes" et "Offres" et  si possible de mettre un trait fin pour séparer ce qui est personnel (mes offres, mes demandes, mon profil...) de ce qui ne l'est pas (Offres, demandes, Maple Chan)

**Comment by AmosTrask** [comment]
Modifier l'ordre doit être possible, le trait aucune idée.
